# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: tcwcsilentauction.us
  secret_key_base: 12a4c411c3e8843c58b5957ef89d71e372f1b8fb26028344c2416460a0d535036e8b74cd79688ec99da7d89c60656736e8384ae5b26d70fe5ded4176c863adcd

test:
  secret_key_base: ce6d5a741efb246c9d2d7c2206281f0b4cbd251453060fe15ac04cbca563438e5677fd9d437a206c2281ac9e488d4f75cff0b51f99831d80f2e7ea14a01e99fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: tcwcsilentauction.us
  secret_key_base: 0b963bc2414cc046279d94434499f09ce094fe6e8634b4d7b59cb9934c6bc1cdd4dde196cc569fa9e40e52db081db44f02cad223ae8e35a6cea01878bbd43d3b
# chazlarson at Gerard.localdomain in ~/dev/ruby/rails-tcwc-r2 on master! [13:56:00]
#  domain_name: <%= ENV["DOMAIN_NAME"] %>
#  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
